# Generated by Django 3.2.25 on 2024-03-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="enquiry_type",
            field=models.CharField(
                choices=[
                    ("PRODUCT_QUERY", "Product Query"),
                    ("ORDER_QUERY", "Order Query"),
                    ("OTHER", "Other"),
                ],
                default="PQ",
                max_length=254,
            ),
        ),
    ]
